#!/usr/bin/env python3
"""Generate the Guide docs from the Sinew design notes.

The design notes are the source of truth. They live in three mirrored trees:

    base/     what and why (shown for every language)
    kotlin/   how in Kotlin (shown when the language switcher is Kotlin)
    flutter/  how in Flutter (shown when the language switcher is Dart)

Each base note becomes one page with a "Concept" part (the base note) and an
"Implementation" part (the Kotlin and Flutter notes, switched by language).
Platform notes are paired with their base note through `implements:` in their
frontmatter, or by the same path. `_spec/` is never read.

Usage (from docs/internal/):

    python3 scripts/sync_vault.py <path-to-sinew-notes>

The generated folder (development/guide) is wiped and rewritten;
development/sidebars.ts builds the sidebar from it. Sinew keeps its overview at the
root of the notes (00 - Overview.md), which becomes the Guide's index page.
"""

from __future__ import annotations

import json
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

DOCS_ROOT = Path(__file__).resolve().parent.parent
# One docs instance (development/) with one sidebar: the Guide.
INSTANCES = {
    "guide": DOCS_ROOT / "development" / "guide",
}
SECTIONS = {"guide": ("Guide", 1)}
PLATFORMS = {"kotlin": ("KotlinOnly", "Kotlin"), "flutter": ("DartOnly", "Flutter")}
# The language switcher stores "kotlin" or "dart"; heading ids use the same prefix
# so the swizzled TOCItems can hide the other language's headings.
ID_PREFIX = {"kotlin": "kotlin", "flutter": "dart"}

GENERATED_NOTICE = (
    "{/* Generated by docs/internal/scripts/sync_vault.py from the Sinew design notes. "
    "Edit the notes and re-run the script; changes made here are overwritten. */}"
)

# Callouts that only record the review process: never published.
DROPPED_CALLOUTS = re.compile(r"^(Open for review|Settled in|Read the base note first)", re.I)
ADMONITION = {
    "info": "info", "important": "info", "note": "note", "abstract": "note",
    "question": "note", "tip": "tip", "success": "tip", "example": "note",
    "warning": "warning", "caution": "warning", "danger": "danger", "bug": "danger",
}

# Sections and markers that only point at the private planning notes or the review history.
DROPPED_SECTIONS = {"Planning documents"}
REVIEW_MARKERS = [
    (re.compile(r",\s*(?:settled|decided) in (?:the \w+ )?review"), ""),
    (re.compile(r"\s*\((?:settled|decided) in (?:the \w+ )?review\)"), ""),
    (re.compile(r"\s*// (?:settled|decided) in (?:the \w+ )?review\s*$"), ""),
]

WIKILINK = re.compile(r"\[\[([^\]|#\\]+)(#[^\]|\\]*)?(?:\\?\|([^\]]*))?\]\]")
DOCLINK = r"\[\[docs/[^\]]+\]\]"


@dataclass
class Note:
    key: str                     # e.g. "base/02 - Packages/03 - Paging"
    title: str
    body: str
    implements: str | None = None


@dataclass
class Page:
    rel: str                     # path below base/, without .md
    concept: Note | None = None
    platforms: dict[str, Note] = field(default_factory=dict)

    @property
    def title(self) -> str:
        if self.concept:
            return self.concept.title
        note = next(iter(self.platforms.values()))
        return re.sub(r"\s*\((Kotlin|Flutter|Dart)\)\s*$", "", note.title)

    @property
    def instance(self) -> str:
        return "guide"

    @property
    def segments(self) -> list[str]:
        parts = self.rel.split("/")
        return parts

    @property
    def is_index(self) -> bool:
        return strip_number(self.segments[-1]) == "Overview"

    @property
    def out_path(self) -> Path:
        dirs = [seg_slug(s, keep_number=True) for s in self.segments[:-1]]
        name = "index" if self.is_index else seg_slug(self.segments[-1], keep_number=True)
        return INSTANCES[self.instance].joinpath(*dirs, name + ".mdx")

    @property
    def slug(self) -> str:
        parts = [seg_slug(s) for s in self.segments]
        if self.is_index:
            parts = parts[:-1]
        return "/" + "/".join([self.instance, *parts])

    @property
    def route(self) -> str:
        return self.slug


# ---------------------------------------------------------------- naming

def number_of(segment: str) -> int | None:
    m = re.match(r"^(\d+)\s*-\s*", segment)
    return int(m.group(1)) if m else None


def strip_number(segment: str) -> str:
    return re.sub(r"^\d+\s*-\s*", "", segment)


def slugify(text: str) -> str:
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", text)
    text = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-")
    return text.lower()


def seg_slug(segment: str, keep_number: bool = False) -> str:
    slug = slugify(strip_number(segment))
    n = number_of(segment)
    return f"{n:02d}-{slug}" if keep_number and n is not None else slug


def heading_id(text: str) -> str:
    text = re.sub(r"`", "", text).lower()
    text = re.sub(r"[^\w\s-]", "", text)
    return re.sub(r"\s+", "-", text.strip())


# ---------------------------------------------------------------- reading

def read_note(root: Path, path: Path) -> Note:
    text = path.read_text(encoding="utf-8")
    implements = None
    if text.startswith("---\n"):
        end = text.index("\n---", 4)
        front, text = text[4:end], text[end + 4:]
        m = re.search(r'^implements:\s*"?\[\[projects/sinew/([^\]]+)\]\]"?', front, re.M)
        if m:
            implements = m.group(1)
    m = re.search(r"^# (.+)$", text, re.M)
    title = m.group(1).strip() if m else strip_number(path.stem)
    body = text[m.end():] if m else text
    key = str(path.relative_to(root).with_suffix(""))
    return Note(key=key, title=title, body=body.strip("\n"), implements=implements)


def collect(root: Path) -> tuple[dict[str, Page], dict[str, Page]]:
    """Returns pages by base-relative path, and a lookup from every note key to its page."""
    pages: dict[str, Page] = {}
    by_key: dict[str, Page] = {}
    overview = root / "00 - Overview.md"          # Sinew keeps its overview at the root of the notes
    if overview.is_file():
        note = read_note(root, overview)
        pages[note.key] = Page(rel=note.key, concept=note)
        by_key[note.key] = pages[note.key]
    for path in sorted((root / "base").rglob("*.md")):
        note = read_note(root, path)
        rel = note.key.removeprefix("base/")
        pages[rel] = Page(rel=rel, concept=note)
        by_key[note.key] = pages[rel]
    for platform in PLATFORMS:
        for path in sorted((root / platform).rglob("*.md")):
            note = read_note(root, path)
            rel = (note.implements or "").removeprefix("base/") or note.key.removeprefix(platform + "/")
            if rel not in pages:
                rel = note.key.removeprefix(platform + "/")
                pages.setdefault(rel, Page(rel=rel))
            pages[rel].platforms[platform] = note
            by_key[note.key] = pages[rel]
    return pages, by_key


# ---------------------------------------------------------------- transforms

def split_code(lines: list[str]):
    """Yields (is_code, line); fenced code blocks are passed through untouched."""
    fence = None
    for line in lines:
        m = re.match(r"^\s*(```+|~~~+)", line)
        if fence is None and m:
            fence = m.group(1)[:3]
            yield True, line
        elif fence is not None:
            if line.strip().startswith(fence):
                fence = None
            yield True, line
        else:
            yield False, line


def convert_callouts(body: str) -> str:
    out: list[str] = []
    lines = body.split("\n")
    i = 0
    dropping = False
    while i < len(lines):
        line = lines[i]
        m = re.match(r"^> \[!(\w+)\][-+]?\s*(.*)$", line)
        if m:
            kind, title = m.group(1).lower(), m.group(2).strip()
            block = []
            i += 1
            while i < len(lines) and lines[i].startswith(">"):
                block.append(re.sub(r"^> ?", "", lines[i]))
                i += 1
            if DROPPED_CALLOUTS.match(title):
                dropping = True
                continue
            dropping = False
            head = f":::{ADMONITION.get(kind, 'note')}" + (f"[{title}]" if title else "")
            out += [head, "", *block, "", ":::"]
            continue
        if dropping:
            # A blank line inside a dropped callout splits it into a second quote block.
            if line.strip() == "":
                j = i
                while j < len(lines) and lines[j].strip() == "":
                    j += 1
                if j < len(lines) and lines[j].startswith(">") and not lines[j].startswith("> [!"):
                    i = j
                    continue
            elif line.startswith(">"):
                i += 1
                continue
            dropping = False
        out.append(line)
        i += 1
    return "\n".join(out)


def strip_vault_links(line: str) -> str:
    """Links into the personal knowledge base are not published."""
    if "[[docs/" not in line:
        return line
    many = rf"{DOCLINK}(?:(?:,\s*|\s+and\s+){DOCLINK})*"
    line = re.sub(rf"\s*(?:-\s*)?(?:\w+\s+)?[Tt]heory(?:\s[^:\[]*)?:\s*{many}\.?", "", line)
    line = re.sub(rf"\s*See {DOCLINK}\.", "", line)
    line = re.sub(rf",\s*{DOCLINK}", "", line)
    line = re.sub(r"\[\[docs/[^\]|]*/(?:\d+ - )?([^\]|/]+)\]\]", r"\1", line)
    return line


def convert_links(line: str, by_key: dict[str, Page], current: Page, warnings: list[str]) -> str:
    def repl(m: re.Match) -> str:
        target, anchor, alias = m.group(1).strip(), m.group(2), m.group(3)
        target = target.removeprefix("projects/sinew/")
        page = by_key.get(target)
        if page is None:
            if not target.startswith("projects/"):
                warnings.append(f"{current.rel}: unresolved link [[{target}]]")
            return alias or strip_number(target.split("/")[-1])
        text = alias or page.title
        href = page.route
        platform = target.split("/")[0]
        if platform in PLATFORMS and page.concept:
            href += "#implementation"
        elif anchor:
            href += "#" + heading_id(anchor[1:])
        if page is current and not anchor:
            return text
        return f"[{text}]({href})"

    return WIKILINK.sub(repl, line)


INLINE_CODE = re.compile(r"(`+)(.+?)\1")


def escape_mdx(line: str) -> str:
    def esc(text: str) -> str:
        text = text.replace("{", "\\{").replace("}", "\\}")
        return re.sub(r"<(?=[A-Za-z/!?])", "&lt;", text)

    out, pos = [], 0
    for m in INLINE_CODE.finditer(line):
        out.append(esc(line[pos:m.start()]))
        out.append(m.group(0))
        pos = m.end()
    out.append(esc(line[pos:]))
    return "".join(out)


def drop_sections(body: str) -> str:
    out, skip_level = [], None
    for is_code, line in split_code(body.split("\n")):
        h = None if is_code else re.match(r"^(#{2,6}) (.+)$", line)
        if h and skip_level is not None and len(h.group(1)) <= skip_level:
            skip_level = None
        if h and h.group(2).strip() in DROPPED_SECTIONS:
            skip_level = len(h.group(1))
        if skip_level is None:
            out.append(line)
    return "\n".join(out)


def strip_review_markers(line: str) -> str:
    for pattern, replacement in REVIEW_MARKERS:
        line = pattern.sub(replacement, line)
    return line


def transform(note: Note, page: Page, by_key: dict[str, Page], warnings: list[str],
              shift: int, id_prefix: str | None) -> str:
    body = convert_callouts(drop_sections(note.body))
    out: list[str] = []
    for is_code, line in split_code(body.split("\n")):
        line = strip_review_markers(line)
        if is_code:
            out.append(line)
            continue
        if "_spec/" in line:
            continue
        original = line
        line = strip_vault_links(line)
        if original.strip() and not line.strip():
            continue
        line = convert_links(line, by_key, page, warnings)
        line = escape_mdx(line)
        h = re.match(r"^(#{2,5}) (.+)$", line)
        if h:
            text = h.group(2)
            line = "#" * min(len(h.group(1)) + shift, 6) + " " + text
            if id_prefix:
                line += f" {{#{id_prefix}-{heading_id(text.replace(chr(92), ''))}}}"
        out.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip("\n")


# ---------------------------------------------------------------- writing

def yaml_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(page: Page, by_key: dict[str, Page], warnings: list[str]) -> str:
    front = ["---", f"title: {yaml_str(page.title)}", f"slug: {yaml_str(page.slug)}"]
    if page.is_index:
        front.append(f"sidebar_label: {yaml_str('Overview')}")
        front.append("sidebar_position: 0")
    front.append("---")
    parts = ["\n".join(front), GENERATED_NOTICE, f"# {escape_mdx(page.title)}"]

    both = page.concept is not None and page.platforms
    shift = 1 if both else 0
    if page.concept:
        if both:
            parts.append("## Concept {#concept}")
        parts.append(transform(page.concept, page, by_key, warnings, shift, None))
    if page.platforms:
        if both:
            parts.append("## Implementation {#implementation}")
        for platform, (tag, label) in PLATFORMS.items():
            note = page.platforms.get(platform)
            content = (transform(note, page, by_key, warnings, shift, ID_PREFIX[platform]) if note
                       else f":::note\n\nThere is no {label}-specific note for this page yet.\n\n:::")
            parts.append(f"<{tag}>\n\n{content}\n\n</{tag}>")
    return "\n\n".join(parts) + "\n"


def write_categories(pages: dict[str, Page]) -> None:
    dirs: dict[Path, str] = {}
    for page in pages.values():
        segs = page.segments[:-1]
        for depth in range(1, len(segs) + 1):
            path = INSTANCES[page.instance].joinpath(*(seg_slug(s, True) for s in segs[:depth]))
            dirs[path] = segs[depth - 1]
    for instance, (label, position) in SECTIONS.items():
        data = {"label": label, "position": position, "collapsible": False}
        (INSTANCES[instance] / "_category_.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    for path, segment in dirs.items():
        data = {"label": strip_number(segment), "position": number_of(segment) or 0}
        (path / "_category_.json").write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def clean(directory: Path) -> None:
    for child in directory.iterdir():
        shutil.rmtree(child) if child.is_dir() else child.unlink()


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    root = Path(sys.argv[1]).expanduser().resolve()
    if not (root / "base").is_dir():
        print(f"error: {root} has no base/ folder", file=sys.stderr)
        return 1

    pages, by_key = collect(root)
    for directory in INSTANCES.values():
        directory.mkdir(parents=True, exist_ok=True)
        clean(directory)

    warnings: list[str] = []
    for page in pages.values():
        page.out_path.parent.mkdir(parents=True, exist_ok=True)
        page.out_path.write_text(render(page, by_key, warnings), encoding="utf-8")
    write_categories(pages)

    merged = sum(1 for p in pages.values() if p.concept and p.platforms)
    print(f"{len(pages)} pages written ({merged} with Kotlin/Flutter implementation parts)")
    for w in warnings:
        print("warning:", w)
    return 0


if __name__ == "__main__":
    sys.exit(main())
