import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated folder (scripts/sync_vault.py): guide/ becomes the one section.
const sidebars: SidebarsConfig = {
  developmentSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
